#!/bin/bash
curl -sSf -u admin:eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJHdWpCZkVHZXhQVk81aXZOd3NUZ0VpT21lLWlsNE1sWXFZU2Vkd1VwT05ZIn0.eyJzdWIiOiJqZmZlQDAwMFwvdXNlcnNcL2FkbWluIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9uc1wvYWRtaW4gYXBpOioiLCJhdWQiOlsiamZydEAqIiwiamZtZEAqIiwiamZldnRAKiJdLCJpc3MiOiJqZmZlQDAwMCIsImlhdCI6MTYwNjk0NDUzMCwianRpIjoiMGM2MTJiMWItYjc0OS00ZWE4LTgwMjEtNDgxMGFhYzgyZmNkIn0.ou4_mbgT1OR-z0xpdDydu42TJdm1vRoF880nL3S40HTBsC2em-AzDd7EUULhj_UWt9MipWCy_oYt8dMFgt99pyttstOWoQB7hIz23UeUIDAbIANuZLmKA9X7WZlS2n4gWLXwRy3e5ySMd72FMoQvSPD1F0T0HBtlfV34JfBO0V-TSkOBvNwuKeqzIlLEWvn32VNUzZSL4iWsh4bTEO6JvEPpiqbVqui88quuuB-_lrWuqYNFV-lfR1g-WjTtW31t9xxVKrdu_IBNz8LwguyzIk1xHowJO11CNTF_y3wF3fkpEjuRcJl605WsaKKhATmuC6dYYmtFRgdFMmWXbFpeOw -O 'http://artifactory.eurustechnologies.info/artifactory/docker-eurus/spring-boot-hello-world-1.0.0-SNAPSHOT.jar'
cd /usr/bin
ls -la
service apache2 restart
