#!/bin/bash
curl -sSf -u admin:eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJHdWpCZkVHZXhQVk81aXZOd3NUZ0VpT21lLWlsNE1sWXFZU2Vkd1VwT05ZIn0.eyJzdWIiOiJqZmZlQDAwMFwvdXNlcnNcL2FkbWluIiwic2NwIjoiYXBwbGllZC1wZXJtaXNzaW9uc1wvYWRtaW4gYXBpOioiLCJhdWQiOlsiamZydEAqIiwiamZtZEAqIiwiamZldnRAKiJdLCJpc3MiOiJqZmZlQDAwMCIsImlhdCI6MTYwNzAxMzQzNCwianRpIjoiZWFlYWE1YTgtNGY5ZC00N2E0LTk4ZDAtMjU1MzI1NmI3OWQxIn0.nY3i0RuKqOyIIj1IZrizEKcUFqXkjXJ0PO9Wcs8CqA6QmxyQOgtVbQbpucu_pxsPrtYZV8l6aq2K5cMNWxwyTAnkcfMq4XI0OVBqPdJG39Qn446MwZacTV5W-3V3F3_ZfJjIw7RWDHWk2VFwNscLlFvb54qhNEQ8Ef3sCg5t9TKOU8Z5DU4wCNcfUUoG3_EJ5e7UGtnyBgCVx6fLJKUA74BFmDmPBcPAmNNB6gDDsGXakEG55T6csXH-trm4P7hkqlLmBi-NR0bTMr1Aslhjq4cT6ZBTxVTpzKiel9lJn_4z_Cl4qrwtrCj4KTtMhzqfhgjY2VMbQGoQjLeG99hh_Q -O 'http://artifactory.eurustechnologies.info/artifactory/docker-eurus/spring-boot-hello-world-1.0.0-SNAPSHOT.{BuildNumber}.jar'
cd /usr/bin
ls -la
sudo systemctl restart httpd
