pipeline {

    agent {label 'jenkins-slave'}
   
    stages {

        stage('build') {
        
            steps {
                withCredentials([string(credentialsId: 'Token', variable: 'SECRET')]) { 
                sh 'whoami'

                sh 'pwd'
                
                sh 'ls'

                sh 'pkill java'

                sh 'echo ${BUILD_NUMBER}'                
               
               sh 'ls -la'
    
               sh  'touch test.txt'

               sh 'scp test.txt jenkins-master.personal:~'
                
                sh 'sleep 20s'
                
                sh ' sed -i s/{BuildNumber}/${BUILD_NUMBER}/g deploy-jenkinsfile/testScript.sh'
                
                sh ' sed -i s/{Token}/${SECRET}/g deploy-jenkinsfile/testScript.sh'
                
                sh ' sed -i s/{BuildNumber}/${BUILD_NUMBER}/g deploy-jenkinsfile/java-webapp.service'

                sh 'sudo scp deploy-jenkinsfile/java-webapp.service jenkins-master.personal:/etc/systemd/system/'

                sh 'cat deploy-jenkinsfile/testScript.sh | ssh jenkins-master.personal /bin/bash'

    }            }

    }

}

}
