pipeline {
    environment {
        BUILD_NUM = ''
    }
    agent any
    tools {
        maven 'maven'
        jdk 'jdk'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        
        stage('Test Path') {
            steps {
                sh 'pwd'
                sh 'ls target/'
            }
        }
        stage ('Publish Artifacts') {
        steps {
            rtUpload (
                buildName: JOB_NAME,
                buildNumber: BUILD_NUMBER,
                serverId: "jenkins-artifactory", // Obtain an Artifactory server instance, defined in Jenkins --> Manage:
                spec: """{
                            "files": [
                                {
                                    "pattern": "target/my-app-1.0-SNAPSHOT.jar",
                                    "target": "docker-maven/my-app-1.0-SNAPSHOT.${BUILD_NUMBER}.jar",
                                    "recursive": "true"
                                }
                            ]
                    }"""   
                )
        }
     } 
    
     stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    serverId: "jenkins-artifactory"
                )
            }
        }
    
  }
}
  